### ISSUE TITLE
Project details . . . Please?

### ISSUE THREAD

**Issue by makervinceco** [Raspberryy/Emulated_USB_Printer#4]
Greetings @Raspberryy !

First, thanks to David Brownell and Craig W. Nadler for the work on this great project!

Next, I have a use case for this project that would involve several different models of printers.  I will be adding each of them to the list of printers in the makefile as my first contribution to this project.

I have been able to make it mostly work by following Craig's original documentation.  I was happy to find this GitHub topic and it looks like it has the answers I need.

I am new to GitHub and cannot seem to find details such as the version of Linux distro used successfully, and any other installed pieces.

What say you?

Peace . . . Vince

**Comment by makervinceco** [comment]
Awww man. . . apologies . . . got so excited to find this topic . . . failed to read . . . closing this non-issue.

**Comment by Raspberryy** [comment]
Hi Vince,
I am glad this project might help you! This project was actually part of my bachelor thesis... Which means I havn't touched it since. Currently I don't have the time to enhance this project, but if you have any working parameters for printer models, I still would love to add them here.

Regarding my setup. I used a Raspberry Pi Zero W and this [USB dongle](https://de.banggood.com/USB-Dongle-With-Acrylic-Shield-for-Raspberry-Pi-Zero-or-Zero-W-p-1432397.html) to easily connect to a PC. I havn't really checked the OS Version. At least not for the git repo.

For converting received print jobs I used GhostPDL. I remember it to be a little difficult to install, but maybe I am wrong here

If you need any help to set this up, feel free to reach out to me :)

**Comment by makervinceco** [comment]
Greetings once again @Raspberryy !

First, thank you for taking the time to reply.  I trust that your bachelor's degree is in hand and that you are well on your way to attaining your master's degree.

I will check in with you from time to time with progress and most definitely want to enhance where I can!

I do have a day job but your work on this has reignited my work on a concept that's been swimmin' in my head for some time . . . thanks again!

GhostPDL is now compiled and ready for testing/troubleshooting.  Biggest challenge was the speed of the pi zero compiling a massive program like "the Ghost".  The make recompile did throw some cc1plus warnings but Google says they shouldn't be a problem.  The fun begins!

I have also acquired the USB dongle mentioned in your reply . . . brilliant!

The long weekend coming up will give me time to focus on this some more.

Peace . . . Vince

**Comment by Raspberryy** [comment]
Haven't started the master yet :( 

GhostPDL only really worked when the printjob contained GhostScript. When PCL was used, the text extraction wasn't working. Converting PCL to PDF however worked good enough with GhostPDL. Dunno what your plans are with this setup. 
The printer that was working best was the RICOH Color Laser AP828. 

Here ist other conversion software you might wannt try if GhostPDL isn't able to interpret your print jobs:

Name 			Website 							Print Job Language
escpos-tools 		github.com/receipt-print-hq/escpos-tools ESC/PO
GhostPDL		www.ghostscript.com/ 				Postscript, PCL, PJL, PDF, PXL, XPS
JetPCL 			www.jetpcl.de 						PCL-4, PCL-5, PCL-5-E, HPGL2, PCL-XL
PCL2PDF 		www.visual.co.uk 					PCL-4, PCL-5, PCL-5-E
RALPage 			ftp.gwdg.de/pub/x11/x.org/R5contrib/ 	PostScript
RedTitan EscapeE 	www.pclviewer.com 					U. a. PostScript, EPS, ESC/P, ESC/P 2, PCL, PCL6, HP-GL
xpost 			github.com/luser-dr00g/xpost 			PostScript

Excited to see any projects using an emulated printer!
